### ISSUE TITLE
Add button to add new post to photo feed layout S8

### ISSUE THREAD

**Issue by mlapresta** [FondApp/Fond#17]
![image](https://user-images.githubusercontent.com/40969859/99158998-52286780-269e-11eb-86da-63eb2aa92fcb.png)

Acceptance Criteria:
- [ ] Button matches user feed wireframe
- [x] onClick, screen changes to photo capture (creation) #16

**Comment by kat-kime** [comment]
Hi @mlapresta -
[I created a separate issue to match the button to wireframe mockup](https://github.com/FondApp/Fond/issues/72). Right now, the button placeholder I have is just a simple text button. I still have to figure out how to use an icon instead.
