### ISSUE TITLE
Create recipe search fragment S10

### ISSUE THREAD

**Issue by mlapresta** [FondApp/Fond#18]
Acceptance Criteria:
 - [x] Search button in bottom nav bar opens recipe layout
 - [ ] Icon fills on recipe layout

Reference:
![image](https://user-images.githubusercontent.com/40969859/99158702-4d15e900-269b-11eb-8870-ec0c5a08ff14.png)

**Comment by GavinSlusher** [comment]
The search icon is the only one w/no outline & filled state. I think this is OK though.
