### ISSUE TITLE
Initialize SDK for Parse

### ISSUE THREAD

**Issue by mlapresta** [FondApp/Fond#2]
Reference: 
[Parse](https://guides.codepath.org/android/Building-Data-driven-Apps-with-Parse#installing-the-parse-sdk)
Acceptance Criteria: 
- [x] Able to verify that Parse is working with the application 
(Note: See [Testing Parse Client](https://guides.codepath.org/android/Building-Data-driven-Apps-with-Parse#testing-parse-client) )

**Comment by kat-kime** [comment]
This was completed as part of #3 and #4
