### ISSUE TITLE
User can login (back end) S2

### ISSUE THREAD

**Issue by mlapresta** [FondApp/Fond#4]
References:
[User login](https://guides.codepath.org/android/Building-Data-driven-Apps-with-Parse#user-session-login) 

Acceptance criteria:
- [x]  User can use a previously created account to login on login/sign up screen
Note: This ticket depends on log in/sign up screen

**Comment by kat-kime** [comment]
Just a heads up:

- When I first started building the LoginActivity class, I received a `com.parse.ParseRequest$ParseRequestException: i/o failure` error when using Fond's Parse credentials. 
- This happened even though the code I used was exactly similar to the Parstagram clone we built.
- I tried using my Parstagram credentials - the login worked.
- Then I used the Fond's credentials again - the login worked! Even though nothing had changed on the backend.
- I'm thinking there was a server issue (perhaps Parse limits our login attempts?).
- In any sense, [I asked the CodePath team here](https://codepath.slack.com/archives/G01DF92D1HS/p1605596144010000). I'll update if I learn anything new.
- But, for now, the login feature is working.

**Comment by mlapresta** [comment]
When I previously had the same error, it was because my emulator had airplane mode on. I wonder if something with the new phone emulator setup hadn't finished setting up yet?

**Comment by kat-kime** [comment]
I got the following message from one of the TAs:

> Hello @kat No, parse does not have a login limit. This is an issue that I too have encountered. Sometimes this issue is caused by not enabling cleartexttraffic or the internet being buggy on the emulator. Others have found that by setting a targetSandboxVersion does away with this error for good.

So, it looks like it might just be a bit buggy. (Also, forgot to mention that I already tried enabling cleartexttraffic to no avail. Ah well!)
